env:
  global:
  - PACKAGE_NAME=chinese2pinyin
before_install:
- export BUILD_VERSION=$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
- export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION.deb
- sudo apt-get update
- sudo apt-get install -y devscripts
script:
- debuild
after_success:
- ls -l $PACKAGE_NAME_VERSION
- md5sum $PACKAGE_NAME_VERSION
after_script:
- |
  echo "Uploading package(s) to ppa ..."
  dput ppa:feng-kylin/test-daily ../*.source.changes || DEPLOY_FAILURE=true;
  if [[ $DEPLOY_FAILURE == 'true' ]]; then echo "Uploading package(s) failed!"; travis_terminate 1; fi;
